config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :pictures do
    collection do
      post :confirm
    end
  end   
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :favorites, only: [:show, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :content, presence: true
  validates :content, length: { in: 1..140 }
  belongs_to :user  
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :image, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :pictures
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader
  has_many :favorite_pictures, through: :favorites, source: :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def set_current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def authenticate_user
    # 現在ログイン中のユーザが存在しない場合、ログインページにリダイレクトさせる。
    if @current_user == nil
      flash[:notice] = 'ログインできませんでした'
      redirect_to new_session_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def show
    @user = current_user
    @favorites = Favorite.where(user_id: @user.id).all
    @pictures = Picture.all
    @pictureId = []
    @favorites.each do |f|
      @pictureId << f.picture_id
    end
  end
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
    before_action :set_current_user, :authenticate_user
    before_action :set_picture, only: [:show, :edit, :update, :destroy]
    before_action :ensure_current_user_picture, {only: [:edit, :update, :destroy]}
  def index
    @pictures = Picture.all 
  end
  def new
    if params[:back]
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end
  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if params[:back]
      render :new
    else
      if @picture.save
        @user=User.find(@picture.user_id)
        ContactMailer.contact_mail(@picture,@user).deliver
        redirect_to pictures_path
      else
        render :new
      end
    end
  end
  def show
    @picture = Picture.find(params[:id])
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end
  def edit
    @picture = Picture.find(params[:id])
  end
  def update
    @picture = Picture.find(params[:id])
    if @picture.update(picture_params)
      redirect_to pictures_path
    else
      render :edit
    end
  end
  def destroy
    @picture.destroy
    redirect_to pictures_path
  end
  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end
  private
  def picture_params
    params.require(:picture).permit(:title, :content, :image, :image_cache)
  end
  def set_picture
   @picture = Picture.find(params[:id])
  end
  def ensure_current_user_picture
    if current_user.id != @picture.user_id
      flash[:notice]="権限がありません"
      redirect_to new_session_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_current_user, :authenticate_user, {only: [:edit, :update, :show]}
  before_action :ensure_current_user, {only: [:edit, :update]}
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  def show
    @user = User.find(params[:id])
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to pictures_path
    else
      render :edit
    end
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :image, :image_cache)
  end
  def ensure_current_user
    if @current_user.id != params[:id].to_i
      flash[:notice]="権限がありません"
      redirect_to new_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    current_user.present? 
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/show.html.erb
<h1 class="title">お気に入り</h1>
  <table>
    <tr>
      <th>ユーザーネーム</th>
      <th>タイトル</th>
      <th>コメント</th> 
    </tr>
    <%@pictureId.each do |id|%>
    <tr>
      <td><%= @pictures.find(id).user.name %></td>
      <td><%= @pictures.find(id).title %></td>
      <td><%= @pictures.find(id).content %></td>
      <td><%= link_to '詳細を確認する', picture_path(id) %></td>
    </tr>
    <% end %>
  </table>
<%= link_to 'プロフィールに戻る', user_path(@user) %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Picturebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <header>
        <ul>
          <li>
            <%= link_to 'ホーム', pictures_path %>
          </li>
          <% if logged_in? %>
            <li class = "log"><%= link_to "プロフィール", user_path(current_user.id) %></li>
            <li class = "log"><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
          <% else %>
            <li class = "log"><%= link_to "サインアップ", new_user_path %></li>
            <li class = "log"><%= link_to "ログイン", new_session_path %></li>
          <% end %>
        </ul>
       </header>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true ,url: choose_new_or_edit ) do |form| %>    
<% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="picture_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="picture_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
   </div>
  <div class="actions">
  <%= form.submit %>
<% end %>
<%= link_to "ピクチャーズ一覧画面にもどる", pictures_path %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p>タイトル:<%= @picture.title %></p>
  <p>本文:<%= @picture.content %></p>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "投稿する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<h2>ピクチャーズを編集する</h2>
  <%= render 'form' %>

app/views/pictures/index.html.erb
<h1 class="title">Picture Rails</h1>
    <table>
      <tr>
        <th>ユーザーネーム</th>
        <th>タイトル</th>
        <th>コメント</th>
      </tr>
        <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.user.name %></td>
        <td><%= picture.title %></td>
        <td><%= picture.content %></td>
        <td><%= link_to '詳細を確認する', picture_path(picture.id) %></td>
        <% if current_user.id == picture.user_id%>
          <td><%= link_to '編集する', edit_picture_path(picture.id) %></td>
          <td><%= link_to '削除する', picture_path(picture.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></td>
        <% end %>
      </tr>
      <% end %>
    </table>
  <%= link_to '新しくピクチャーズを投稿する', new_picture_path %>
  <footer class="footer">
    <p>Copyright © 2020 株式会社Wing</p>
  </footer>

app/views/pictures/new.html.erb
<h3>ピクチャーズを作成する</h3>
  <%= render 'form' %>

app/views/pictures/show.html.erb
<h3>ブログ詳細画面</h3>
<p>タイトル: <%= @picture.title %></p>
<p>内容: <%= @picture.content %></p>
<p id="notice"><%= notice %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @picture.image.url %>
</p>
<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<%= link_to '編集', edit_picture_path(@picture) %> |
<%= link_to '戻る', pictures_path %>

app/views/users/edit.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
　<div class="field">
    <%= f.label :image %>
    <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
　</div>
　<%= f.label :password %>
　<%= f.password_field :password %>
　<%= f.label :password_confirmation %>
　<%= f.password_field :password_confirmation %>
　<%= f.submit "Create my account" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @user.image.url %>
</p>
<%= link_to 'お気に入り一覧', favorite_path(@user.id) %> |
<%= link_to 'プロフィールを編集する', edit_user_path(@user) %> |
<%= link_to "ピクチャーズ一覧画面にもどる", pictures_path %>